### ISSUE TITLE
Regression on Windows

### ISSUE THREAD

**Issue by rifraf** [pderichs/sublime_rubocop#22]
Commit 5815543432b9c745ccbdd386fcbc94a620699973 removes lines added for Windows support in cb60ac35e2d246a026016894bdf71ce4872e7fca

Consequence: sublime_rubocop doesn't work nice in Windows again :-( 

(Putting the 3 lines back in works on latest version)

**Comment by pderichs** [comment]
The commands should be working again but I did not manage to make mark issues in view working until now. I opened a new issue for that: https://github.com/pderichs/sublime_rubocop/issues/29
