### ISSUE TITLE
Non .rb files are not auto-checked

### ISSUE THREAD

**Issue by mtarnovan** [pderichs/sublime_rubocop#33]
If I understand [this code](https://github.com/pderichs/sublime_rubocop/blob/master/file_tools.py#L20), auto-checks only run on `.rb` files. If not too complicated, I suggest parsing rubocop.yml and extracting the `AllCops: Include` and `AllCops: Exclude` rules,  (see https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L9-29) and use that in the `is_ruby_file` method. 

If that's too complicated, adding some other extension to that list might be a good fallback (`.gemspec, Gemfile, .rake` etc). 

Sorry for not sending a PR, I don't know Python. Kudos for a very useful plugin.

**Comment by mtarnovan** [comment]
Another good alternative would be to ask Sublime of the current file type is Ruby or Rails, I think that might be possible through the Sublime Plugin API.

**Comment by nopc0de** [comment]
+1

**Comment by pderichs** [comment]
@mtarnovan you are absolutely right - thanks for reporting that issue!

It should be fixed by now - I chose your second suggestion for a solution :wink: .

Glad you like the plugin :) 

Cheers!

**Comment by mtarnovan** [comment]
@pderichs Thanks for the fix. I suggest adding `RSpec.tmlanguage` to the list of syntaxes recognized as Ruby.
