### ISSUE TITLE
mark_issues_in_view not working with Sublime Text 3 build 3103

### ISSUE THREAD

**Issue by stephenla** [pderichs/sublime_rubocop#40]
After upgrading to build 3103, I noticed that issues are no longer marked in the Sublime view. However, Rubocop still works and outputs in the console.

**Comment by pderichs** [comment]
Thanks for reporting. Should be fixed now.

**Comment by iagopiimenta** [comment]
@pderichs Does not work with those who have not updated, it is best to consider [higher versions or equal](https://github.com/pderichs/sublime_rubocop/blob/master/file_tools.py#L5) to 3103. Until the 3103 version still uses the old template syntax.
